### ISSUE TITLE
How do I install the plugin to NeoVim

### ISSUE THREAD

**Issue by h-khoza** [cohama/lexima.vim#102]
I am new to open source, and I am not familiar with building from source, I would instruction step by step on how to install this plugin on Neovim

**Comment by cohama** [comment]
lexima.vim is written in pure vim script and you do not need to build this plugin.
You can install this by typical plugin manager such as [vim-plug](https://github.com/junegunn/vim-plug) or [dein.vim](https://github.com/Shougo/dein.vim).

First, you need to install plugin manager. Read the installation instruction of the plugin manager you choose.
Second, add installation code to your vimrc by your plugin-manager's manner.
For example, if you use vim-plug, write the following line in your `.vimrc` (`~/config/nvim/init.nvim`) file.

```vim
Plug 'cohama/lexima.vim`
```

**Comment by h-khoza** [comment]
Thank you
