### ISSUE TITLE
The closing character is succeeded by: `«»`

### ISSUE THREAD

**Issue by AnatoleLucet** [cohama/lexima.vim#113]
This plugin looks great! I'm just having a small issue with it.

I think it'll be easier to explain via a gif:
![Peek 2021-05-31 12-24](https://user-images.githubusercontent.com/35486736/120179689-31bf9500-c20b-11eb-998e-83f38f9e9f30.gif)

When I don't write the closing parenthesis, I'm ending up with these strange `«»`. It's also the case for any other "closable" character (e.g. `"`, `{`).

**Comment by cohama** [comment]
Probably,  it is caused by other plugin. I can not repro.

Please report your vimrc. (minimal one is better)
