### ISSUE TITLE
indentation failed after pressing <CR> between brackets

### ISSUE THREAD

**Issue by alexzanderr** [cohama/lexima.vim#114]
hi.

nice plugin. works great, but..

when i do this:
![lexima-issue1](https://user-images.githubusercontent.com/54772464/122062621-3f267300-cdf8-11eb-86ee-0e871787a6c2.png)

i get this:
![lexima-issue2](https://user-images.githubusercontent.com/54772464/122062673-4baacb80-cdf8-11eb-9a32-5cc6753cc392.png)

and i was expecting this:
![lexima-issue3](https://user-images.githubusercontent.com/54772464/122062691-4f3e5280-cdf8-11eb-9494-843999879d45.png)

however, when i save the file (python) the auto-formatter is handling by default wrong indented blocks of code.

when i save i get this:
![lexima-issue3](https://user-images.githubusercontent.com/54772464/122062871-77c64c80-cdf8-11eb-9ba1-a0ebeddc2f2c.png)

my indent tab size is set to `4`, but lexima autoindents with tabspace=`8` 

another situation.
when i do this:
![image](https://user-images.githubusercontent.com/54772464/122063261-c542b980-cdf8-11eb-817b-b83c6dcbae6e.png)

unfortunatelly i get this:
![image](https://user-images.githubusercontent.com/54772464/122063323-d4c20280-cdf8-11eb-942e-1e7b9ecccc0a.png)

why is this happening? its vimrc tab settings? its the plugin?

any help? thanks.

**Comment by cohama** [comment]
I could not reproduce it. (Are you writing a python file?) 

Please report your (minimal) vimrc.

**Comment by alexzanderr** [comment]
honestly the problem went away and i dont know how. maybe because it was a plugin interference
