### ISSUE TITLE
[question] how do i represent end of line in lexima rules?

### ISSUE THREAD

**Issue by alexzanderr** [cohama/lexima.vim#118]
i want to tell lexima to add double quotes when the cursor if right before end of line, because normally:

before inserting double quotes:
```
text text text |\n
```

after inserting double quotes:
```
text text text "|\n
```
ony this happens...

expectation (after inserting double quotes):
```
text text text "|"\n
```

this is my rule
```vimL
call lexima#add_rule({'char': '"', 'at': '\%# (here how do i represent new line)', 'input_after': '"'})
```

thanks in advance.

**Comment by cohama** [comment]
Please use `$` which represents the end-of-line.

```vim
call lexima#add_rule({'char': '"', 'at': '\%#$', 'input_after': '"'})
```

By the way, are you going to edit vim script? `"` will be expanded always except vim script because `"` is treated as a comment.

**Comment by alexzanderr** [comment]
thanks for idea. yes, my bad, i forgot to mention that i was writing in vim
script, but i realized later.
