### ISSUE TITLE
Nix rule breaks plugin

### ISSUE THREAD

**Issue by ymarkus** [cohama/lexima.vim#122]
When I add this rule:
```
call lexima#add_rule({'char': "''", 'input_after': "''", 'filetype': 'nix'})
```
the plugin does this:
https://user-images.githubusercontent.com/62380378/141512055-74fcf878-c96b-4d6d-a55f-ae1381e0ee4b.mp4

This is the exact text it inserts:
```
pumvisible() ? "\{" : lexima#expand('
      ', 'i')
```

**Comment by cohama** [comment]
I can't repro. Please report minimal vimrc.
