### ISSUE TITLE
= setpos ('.', [0, 1, 1, 0])? '': '' appears in the command line when exiting insert mode 

### ISSUE THREAD

**Issue by jpasquier** [cohama/lexima.vim#127]
Hi,

Thank you for the plugin.

If the option `noshowmode` is active, then `= setpos ('.', [0, 1, 1, 0])? '': ''` appears in the command line when exiting insert mode.

I use neovim 0.4.4 with vim-plug. I get the same issue with the last version (0.6.1).

Minimal `init.vim`:

```
set noshowmode
call plug#begin('~/.local/share/nvim/plugged')
Plug 'cohama/lexima.vim'
call plug#end()
```

Steps to reproduce: open a blank file, enter insert mode, leave insert mode.

It's not a big deal, just a little visual annoyance.

Best regards

**Comment by cohama** [comment]
Thank you for reporting.
I have just fixed.
