### ISSUE TITLE
Prelude.vim has vim type variables that are not supported by version 7.4

### ISSUE THREAD

**Issue by fharvell** [cohama/lexima.vim#128]
Suggested change in Prelude.vim at line 21:

```
" Wrapper functions for type().
" 7.4 does not have vim type variables
let [
\   s:__TYPE_NUMBER,
\   s:__TYPE_STRING,
\   s:__TYPE_FUNCREF,
\   s:__TYPE_LIST,
\   s:__TYPE_DICT,
\   s:__TYPE_FLOAT] = [
      \   exists('+v:t_number') ? v:t_number : 0,
      \   exists('+v:t_string') ? v:t_string : 1,
      \   exists('+v:t_func') ? v:t_func : 2,
      \   exists('+v:t_list') ? v:t_list : 3,
      \   exists('+v:t_dict') ? v:t_dict : 4,
      \   exists('+v:t_float') ? v:t_float : 5]
```

**Comment by cohama** [comment]
Thank you for your report.

lexima.vim no longer supports vim 7.x.

I will add vim requirements in documents.

**Comment by fharvell** [comment]
Cohama,

  With that one change, lexima.vim still appears to work fine (at least in the vim 7.4 version in RHEL 7.9). Would it be possible to put that change in place? I am unable to move past RHEL 7.9 at my work.

  Thank you for your consideration.

Regards,
  F

--
Mr. F Harvell
siteservices.net, Inc.
321 831-8440 • ***@***.*** • www.siteservices.net

**Comment by cohama** [comment]
No. It is a part of [vital.vim](https://github.com/vim-jp/vital.vim), which is vim script library.

**Comment by fharvell** [comment]
Cohama,

  Thank you. I appreciate your response.

Regards,
  F

--
Mr. F Harvell
siteservices.net, Inc.
321 831-8440 • ***@***.*** • www.siteservices.net
