### ISSUE TITLE
日本語入力が途中で確定されてしまう

### ISSUE THREAD

**Issue by YoshihiroIto** [cohama/lexima.vim#13]
便利なプラグインありがとうございます。

日本語入力が途中で確定されてしまう問題に遭遇しました。

++++++++++++++++++
環境:
vim : macvim kaoriya 7.4 1-527
OS : Mac OSX Yosemite
インプットメソッド : GoogleJapaneseInput-2.16.2007.101
+++++++++++++++++++

1)gvim上の挿入モードに移行。インプットメソッドを日本語入力に設定
2)「あいうえお」(aiueo)と入力しようとする

望まれる動作としてEnterキー押下で確定になりますが、
lexima.vimを読み込んでいると、
「あい」入力時点で確定されたことになり、バッファに出力されてしまいます。

インプットメソッド関係の設定

``` vim
set noimdisable
set imsearch=0
set iminsert=0
if exists('+imdisableactivate')
  set imdisableactivate
endif
```

手元gvimで再現率は100%で再現し、iTerm2上のvimでは再現しませんでした。

**Comment by ujihisa** [comment]
ちょっとトリッキーだけど、パッチが取り込まれるまでの間は (というかそれまでのバージョンでは) 日本語入力がオンにときにleximaを無効化するなどの処理を入れると便利そうな予感。

**Comment by ujihisa** [comment]
https://github.com/vim-jp/issues/issues/545 https://github.com/vim-jp/issues/issues/874#issuecomment-326138353

2017-08-31, vim 8.0.1026 で解決しました。本件closeしてよさそうです!
