### ISSUE TITLE
[Feature Request] Add g:lexima_manually_keys

### ISSUE THREAD

**Issue by 4513ECHO** [cohama/lexima.vim#132]
## Motivation

lexima binds mapping automatically in `lexima#add_rule()`.
But it sometimes comes into conflict with other plugins or configs.
We want the way to avoid this problem.

## Feature Overview

We can define `g:lexima_manually_keys` which is list of keys. lexima does not bind to these keys. Users have to use `lexima#expand()` by thereselves.

Example is here:

```vim
let g:lexima_manually_keys = ['$', '<CR>']

call lexima#add_rule({ 'char': '$', 'some': 'config })
call lexima#add_rule({ 'char': '<CR>', 'some': 'config })

inoremap <expr> $ DollarFunc()
cnoremap <expr> <CR> CRFunc()

function! DollarFunc() abort
  if some#condition()
    return some#function()
  endif
  return lexima#expand('$', 'i')
endfunction
```

**Comment by cohama** [comment]
I'm not sure why `g:lexima_manually_keys` is necessary.
In your example, `inoremap <expr> $ DollarFunc()` overrides `$` rules defined by lexima.vim.

**Comment by 4513ECHO** [comment]
Yes, surely we can override mappings if we execute `*(nore)map` after lexima defined rules.
However, if lexima is made lazy by plugin manager, understanding "after lexima defined rules" is hard for most users....
It is important for lexima not to bind mappings certainly.

**Comment by cohama** [comment]
In my opinion, it is hard for most users to understand *lazy* feature is hard and the best solution to such a situation is to not using lazy feature.

**Comment by 4513ECHO** [comment]
Hmm, your opinion is true. The lazy feature is advanced.
However, the most important problem is that lexima define mappings **implicitly**. There are many related issue in the repository about conflict of mappings. It is serious not also for advanced users but beginners.
If the way exists to avoid conflict with other plugins or configs **explicitly**, we can reduce such problems.

**Comment by 4513ECHO** [comment]
Is there any update on this?
If you don't want to include this feature, I'll close this issue. Otherwise I'll send a PR.

**Comment by cohama** [comment]
I'm sorry to slow response. Yes, I can not believe this feature best solution to solve this problem.

**Comment by 4513ECHO** [comment]
Ok, thanks.

**Comment by cohama** [comment]
As discussed vim-jp slack, I finally found out that there are some cases adding a rule and resolving conflicts want to be done independently.
