### ISSUE TITLE
The "at" rule does not support \V in command-line mode

### ISSUE THREAD

**Issue by siaa4fu** [cohama/lexima.vim#139]
When the rule is enabled on command-line mode,
the regular expression set in "at (lexima-rules-at)" does not support **\V**

e.g.

``` vim
" NG: do not work
call lexima#add_rule(#{ char: '.', at: '\V. \%#', input: '<BS>', mode: 'c' })

" OK: but verbose expression
call lexima#add_rule(#{ char: '.', at: '\V. \m\%#', input: '<BS>', mode: 'c' })

" OK: ... I want to use \V
call lexima#add_rule(#{ char: '.', at: '\. \%#', input: '<BS>', mode: 'c' })
```

Thanks for the nice plugin!

**Comment by cohama** [comment]
Thank you for reporting. I have just fixed.

**Comment by siaa4fu** [comment]
Thank you for your fixing.

I tried adding rules in the latest version, but there seems to be a problem with the cursor position.

``` vim
call lexima#add_rule(#{ char: '(', at: '\V(\%#)', input: '', delete: 1, mode: 'c' })
```

If an above rule is defined and

```
()(|
   ^ '(' is inputted at this cursor position,

()|
  ^ the rule is applied incorrectly.
```

One more thing I found that the 'except' is not working in command-line mode.

Sorry for asking too much.

**Comment by cohama** [comment]
Thank you.

> 'except' is not working in command-line mode.

This seems to be other problem. I open a new issue.

**Comment by cohama** [comment]
I will check cursor position problem
