### ISSUE TITLE
Abbreviations are not expanded in command-line mode

### ISSUE THREAD

**Issue by siaa4fu** [cohama/lexima.vim#141]
`lexima#expand({char}, ':')` does not expand abbreviations in command-line mode.

The <C-]> prehook is added in `lexima#cmdmode#add_rules()`, but it doesn't seem to be used.
`g:lexima_disable_abbrev_trigger` is also not used in command-line mode.

Thank you.

**Comment by cohama** [comment]
Thank you!
`prehook` on cmdline works now and `g:lexima_disable_abbrev_trigger` as well.
