### ISSUE TITLE
"LISP mode"? don't pair singlequote or backtick in certain filetypes

### ISSUE THREAD

**Issue by alxndr** [cohama/lexima.vim#148]
Curious if there's a way to leave most of the default rules intact, but "turn off" the pairing completion for singlequote `'` and backtick <code>`</code>, for LISP-based filetypes such as Racket and Scheme?

**Comment by cohama** [comment]
You can use the following.
`call lexima#add_rule(#{ char: "'", input: "'", input_after: "", mode: 'i', filetype: ["racket", "scheme"})`

Removing default rule is difficult but you can overwrite with NOOP.

**Comment by alxndr** [comment]
Thanks @cohama ! I seem to have gotten the behavior I was after with these:
```
  call lexima#add_rule({ 'char': "'", 'filetype': ['lisp', 'scheme', 'racket']})
  call lexima#add_rule({ 'char': '`', 'filetype': ['lisp', 'scheme', 'racket']})
```
