### ISSUE TITLE
There is no lexima-key-mappings section in the document

### ISSUE THREAD

**Issue by eight04** [cohama/lexima.vim#149]
According to the TOC:
https://github.com/cohama/lexima.vim/blob/b1e1b1bde07c1efc97288c98c5912eaa644ee6e1/doc/lexima.txt#L32
There should be a lexima-key-mappings section.

**Comment by cohama** [comment]
Oops!
This section should be removed because no optional mapping (e.g. `<Plug>`) does not exist.

**Comment by eight04** [comment]
I think it would be very helpful to have a list of functions that can be used in key mapping. For example: https://github.com/cohama/lexima.vim/issues/83#issuecomment-500688979
