### ISSUE TITLE
Package for luarocks

### ISSUE THREAD

**Issue by sahinf** [cohama/lexima.vim#153]
Hi, 

Would you consider packaging this nvim plugin to [LuaRocks](https://luarocks.org/) so that the package manager [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) can detect it?
The `rocks.nvim` team [prepared a github action](https://github.com/nvim-neorocks/luarocks-tag-release) that automates this process.

**Comment by cohama** [comment]
I won't do for now.
