### ISSUE TITLE
breaks undo

### ISSUE THREAD

**Issue by justinmk** [cohama/lexima.vim#2]
This looks like a promising plugin. I would like to make you aware of https://github.com/Raimondi/delimitMate/issues/138 which has discussion about fixing undo/redo with these types of plugins. I just tried lexima.vim, and although dot-repeat seems to work, it still breaks undo.

The key to solving undo/redo is in this comment: https://github.com/Raimondi/delimitMate/issues/138#issuecomment-35458273

There is an edge case with visual-block mode: https://github.com/Raimondi/delimitMate/issues/138#issuecomment-35582130

But fixing undo is vastly more important in my opinion. No one has taken the time to implement the solution yet, though.

**Comment by dai-shi** [comment]
Hi, I'm not familiar with this issue, but is this related?
http://code.google.com/p/vim/issues/detail?id=202

**Comment by justinmk** [comment]
@dai-shi no

**Comment by chrisbra** [comment]
Note: Starting from version [7.4.849](https://github.com/vim/vim/releases/tag/v7.4.849) you can use `<C-G>Cursor` to move within a line and not break undo/redo

**Comment by cohama** [comment]
Thanks. You mean `<C-G>U`
I have already know that and I will try to implement in a future version.

**Comment by stjepang** [comment]
Any updates on this? Is there perhaps a workaround for this problem?

**Comment by nhooyr** [comment]
Checkout https://github.com/Raimondi/delimitMate/pull/227

**Comment by kutsan** [comment]
It's been nearly four years since the issue created. It was a promising plugin among other ones, so bad I can't use it because of this problem.

Friendly ping @cohama.

**Comment by mattn** [comment]
A cause of breaking undo is calling `setline` while inserting via `\<C-r>=`.

**Comment by cohama** [comment]
I'm sure that.

In historically reason, lexima uses `setline` to achieve dot-repeat feature and my implementation heavily depends on it.

Sorry for slow response and I will try re-implementation for this issue on this week.
@kutsan

**Comment by Yodzorah** [comment]
Any progress yet?

**Comment by Yodzorah** [comment]
I'm not sure if it helps, but: https://github.com/tpope/vim-repeat

**Comment by cohama** [comment]
No, sorry. This problem is very difficult for now.

**Comment by stjepang** [comment]
@cohama Thanks for the update! And no worries, your plugin is very much appreciated!

If it helps anyone, I have switched to a simple solution that is not quite as good as this plugin but works okayish:

```vim
" Complete braces on <CR> in a sensible way
function! s:complete_braces()
  let line = getline('.')
  let col = col('.')
  if col < 1000 && col == len(line) + 1 && matchstr(line, '\%' . (col-1) . 'c.') == '{'
    return "}\<C-o>k\<C-o>A\<CR>"
  endif
  return ""
endfunction
inoremap <buffer><expr><CR> "\<CR>" . <SID>complete_braces()
```

It shouldn't be too hard to extend this manually for slightly more complicated cases...

**Comment by cohama** [comment]
Hi everyone. I have updated lexima.vim and partially fix this problem.

lexima.vim does not break undo until `<CR>` input.

`hoo(bar(ok))` can be done undo in one step.
