### ISSUE TITLE
Allow this plugin to be disabled per buffer

### ISSUE THREAD

**Issue by dan-silva** [cohama/lexima.vim#20]
First of all... thank you! This plugin is impressive and I found it a lot more flexible/powerful than the any of the alternatives... really, thank you for the effort :)

As this plugin conflicts with some features of [paredit.vim](https://github.com/kovisoft/paredit) (it provides superpowered bindings for brackets/square brackets/parens for LISP dialects), maybe it would be better to allow this plugin to be disabled per buffer, e.g.:
```
autocmd FileType clojure let b:lexima_enabled=0
```

So we can use each one where it fits better.

**Comment by cohama** [comment]
It's a nice idea! I will try.

**Comment by cohama** [comment]
I have implemented `b:lexima_disabled`.
You can use this as following
```vim
autocmd FileType clojure let b:lexima_disabled=1
```
Because your motivavtion is 'want to disable lexima', setting `b:lexima_disabled=1` is natural.

**Comment by dan-silva** [comment]
Thank you! :D
