### ISSUE TITLE
<C-h> mapping

### ISSUE THREAD

**Issue by perrin4869** [cohama/lexima.vim#23]
Hi, I was just wondering about the `<C-h>` mapping in the plugin. I found that in line 99 of `autoload/lexima` you are mapping `<C-h>` to `<BS>`... only it conflicts with another mapping of mine, so it's a problem. I do not see the relevance of the mapping... is there a reason why it's there?

**Comment by cohama** [comment]
I thought most of users use <C-h> as <BS> but I become aware this is wrong.
From now, `<C-h>` mappings are not defined by default if you already have a `<C-h>` mapping.

**Comment by perrin4869** [comment]
Hm... this does not solve the problem actually. The thing is that I am not setting the mapping manually, I am passing <C-h> to YouCompleteMe as an option, and it sets the mapping... only it appears to load after lexima, and therefore the mapping that I want is never set. I am using pathogen for managing my plugins and I have no way to configure the load order... maybe an explicit option for enabling/disabling the mapping would do in this case?

```
let g:lexima_enable_bs_mapping = 1
```

The other question would be... Why is this mapping inside the plugin to begin with?

**Comment by cohama** [comment]
Does not YouCompleteMe override lexima's mapping?

> The other question would be... Why is this mapping inside the plugin to begin with?
Because some people think `<C-h>` is same as `<BS>`.

**Comment by perrin4869** [comment]
No it doesn't... but in any case, I don't think the mapping really belongs in this plugin, if someone wants to map `<C-h>` to `<BS>` they can do that in their vimrc... I don't get why it's part of this plugin

**Comment by cohama** [comment]
I have decided to delete `<C-h>` mappings and to add tips to doc.
If someone complain about this, I will consider this solution again.
