### ISSUE TITLE
delete + input_after not working

### ISSUE THREAD

**Issue by cpixl** [cohama/lexima.vim#25]
I have the following settings:

```
{'char': '<cr>', 'at': '{\%#}$', 'input': '<cr>\<space>', 'input_after': ',<cr>\', 'filetype': 'vim'},
{'char': '<cr>', 'at': '{ \%# }$', 'input': '<bs><cr>\<space>', 'input_after': ',<cr>\', 'delete': 1, 'filetype': 'vim'},
```

The first one works correctly, but the second one doesn't. The behavior (just to make it easier to read) should be like this:

```
Before           Input         After
-----------------------------------------
let a = {|}     <cr>          let a = {
                                \ |,
                                \}
-----------------------------------------
let a = { | }   <cr>          let a = {
                                \ |,
                                \}
```

In the end, both would do the same... de only difference is that the second one handles the `{ | }` case, that's very common on my case.

**Comment by cohama** [comment]
Thank you for your reporting.

I have updated and you can use both "delete" and "input" at the same time.
