### ISSUE TITLE
Characters after cursor deleted in error in a C style function scope due to bad rule

### ISSUE THREAD

**Issue by raymond-w-ko** [cohama/lexima.vim#26]
For example, if you have:
```php
function dummy() {
(asd|)
}
```
and you press ```<BS>``` once the right paren ')' get deleted when it is not suppose to. The cause is the bad rule below which is causing overmatching. Escaping the ```[]``` characters fixes it. Please check.

```diff
diff --git a/autoload/lexima.vim b/autoload/lexima.vim
index 82bff0f..f41e8e6 100644
--- a/autoload/lexima.vim
+++ b/autoload/lexima.vim
@@ -84,7 +84,7 @@ let g:lexima#space_rules = [
 \ {'char': '<Space>', 'at': '{\%#}', 'input_after': '<Space>'},
 \ {'char': '<BS>', 'at': '{ \%# }', 'delete': 1},
 \ {'char': '<Space>', 'at': '\[\%#\]', 'input_after': '<Space>'},
-\ {'char': '<BS>', 'at': '[ \%# ]', 'delete': 1},
+\ {'char': '<BS>', 'at': '\[ \%# \]', 'delete': 1},
 \ ]


```

**Comment by szw** [comment]
The same happens with `"` characters.

**Comment by cohama** [comment]
Thank you for reporting this issue. I have fixed.
Actually, escaping `]` is unnecessary when `[` has already espaced.

> The same happens with " characters.

I tried `"` case but nothing happened. Could you please tell me what the problem is

**Comment by szw** [comment]
Ok, here's explanation: https://asciinema.org/a/7yaq47mccv1dpv3r72ybyo5mx
