### ISSUE TITLE
Space rules break abbreviations

### ISSUE THREAD

**Issue by noahfrederick** [cohama/lexima.vim#27]
Since https://github.com/cohama/lexima.vim/commit/5498cff8ebc449600d510cc3d77f6256188938dc insert-mode abbreviations are no longer expanded when typing `<Space>`. Abbreviations expand as expected by reverting to the previous commit or setting `g:lexima_enable_space_rules = 0`.

## Example

```vim
:iabbrev test testxxx
itest foo<Esc>
```

Result with `g:lexima_enable_space_rules = 0`:

```
testxxx foo
```

Result with `g:lexima_enable_space_rules = 1`:

```
test foo
```

**Comment by cohama** [comment]
Now I have fixed this issue. Please try.

**Comment by noahfrederick** [comment]
Confirmed fixed. Thanks.
