### ISSUE TITLE
Syntax blacklisting

### ISSUE THREAD

**Issue by cpixl** [cohama/lexima.vim#29]
While the `syntax` option is really useful, currently it is not possible to set any "blacklisted" syntax, where the rule shouldn't apply.

It would be really helpful on code-specific situations e.g. the rule inputs a `<cr>` expecting the next line to become indented, but the rule shouldn't apply inside comments (where a `<cr>` would start the next line as the comment continuation or an `<cr>` on `input_after`... both probably breaking the indentation).

**Comment by cohama** [comment]
Please use `except`.
See `:help lexima-rules-except`.
