### ISSUE TITLE
Adding all tpope/endwise default rules

### ISSUE THREAD

**Issue by Hotschke** [cohama/lexima.vim#31]
I try to reduce the number of vim plugins I use. Therefore I'd like to see that all default endwise rules are also shipped with lexima.vim. I would assume that is not too daunting. What is your opinion about this?

**Comment by cohama** [comment]
Yes you are right. But actually lexima.vim provides endwise rules only for major languages. (Ruby, sh, vim script)
Because I am not familier with other languages and I thought other languages' rule are harly used.

**Comment by Hotschke** [comment]
I understand. I would assume that https://github.com/tpope/vim-endwise/blob/master/plugin/endwise.vim tells you everything to know to implement these rules. However, knowing a little bit more would be reasonable.

I am interested in snippet and htmldjango. When I find the time, I will create a pull request.

Thanks.

**Comment by cohama** [comment]
OK, pull req is always welcome!

**Comment by cohama** [comment]
any updates?
