### ISSUE TITLE
Breaks abbreviations triggering on rule-chars

### ISSUE THREAD

**Issue by DeX3** [cohama/lexima.vim#42]
Normally, pressing `(` in insert mode also triggers vim's abbreviations (`:help abbreviations`). With lexima (and its default rules in place), this is no longer the case.

Is there a way to make abbreviations work with lexima?

**Comment by cohama** [comment]
Thanks. I have just fixed.
Please note that abbreviation expansion is enabled on Vim 7.3.489 or later.

**Comment by DeX3** [comment]
Awesome :+1: - Thanks!
