### ISSUE TITLE
Conflict with deoplete and pressing <CR> on completion

### ISSUE THREAD

**Issue by compressed** [cohama/lexima.vim#43]
Hi,
Thanks for the plugin!

I recently updated lexima and found that when I press enter on a [deoplete](https://github.com/Shougo/deoplete.nvim) autocompletion (in insert mode), the completion is no longer inserted into the text. I traced it back to [this change](https://github.com/cohama/lexima.vim/commit/9b77b93b7eec16730e6e4d315fa955dc04034320#diff-a9bc78cc087ace494eeffb1d96015a96R36). I believe it happens because deoplete uses abbreviations in the pop-up menu causing some sort of conflict...

Any ideas for a workaround? Also I'm using neovim. Let me know if you need more info.

Thanks!

**Comment by cohama** [comment]
Sorry for slow respose.
Recently I installed neovim and deoplete and try it but I can not repoduce it.
Please tell me your settings about lexima and deoplete.

**Comment by compressed** [comment]
Thanks for trying! Here are some more details:

```vim
filetype off                  " required

call plug#begin('~/.vim/plugged')
  Plug 'cohama/lexima.vim'
  " Plug 'cohama/lexima.vim', { 'commit': '155dc98220e0bab9c0bfd5090547ef8c4bbaf0be' } (breaks after this commit)
  Plug 'Shougo/deoplete.nvim'
    let g:deoplete#enable_at_startup = 1
" Add plugins to &runtimepath
call plug#end()

filetype plugin indent on    " required
```

Here's a gif showing what's happening. In the first case I have the lexima commit specified, where it's working as I'd expect - hitting `enter` completes. In the second case, using the latest lexima version, whenever I hit `enter` on a match, it just makes a new line, no completions.

![lexima](http://g.recordit.co/gmmbsABtvo.gif)

**Comment by cohama** [comment]
Thanks for details.
I noticed that abbreviation expansion conflicts with popup menu.
It was difficult to solve it but I finally realized it!

Please update to the latest version!

**Comment by compressed** [comment]
Thank you very much! This works perfectly for me now, much appreciated!
