### ISSUE TITLE
Typing quotes in replace mode does not overwrite

### ISSUE THREAD

**Issue by thirtythreeforty** [cohama/lexima.vim#46]
If I have this document:

```
|This is a document.
```

and have the cursor (`|`) at the beginning, entering replace mode and typing `"` causes the single character to be inserted:

```
"|This is a document.
```

I would expect lexima.vim to be disabled in replace mode.  Is this behavior by design?

**Comment by cohama** [comment]
This is not intended. This is a bug.
It should be disabled in replace mode.

**Comment by thirtythreeforty** [comment]
Awesome, thanks!
