### ISSUE TITLE
Space is broken in text/mail format

### ISSUE THREAD

**Issue by h3st** [cohama/lexima.vim#47]
Given
-----

* neovim 0.1.1
* the following init.vim:

        call plug#begin()
        Plug 'cohama/lexima.vim'
        call plug#end()

* Any filetype of "", "text", or "mail" (may be present in other filetypes)

Then
---

The input

    hello␣world

produces the output

    helloworld␣

where `␣` denotes a space.

Workaround
---

The behavior disappears if `lexima_enable_space_rules = 0`, or all three of the `<Space>` rules are deleted from `lexima.vim`; any one of them remaining is enough to trigger the behavior.

**Comment by h3st** [comment]
Oh, forgot to say something about cursor placement. The behaviour exhibited is that spaces are added *after* the cursor. So `aa|` with input `<Space><Space><Space>` yields `aa|␣␣␣`.

**Comment by cohama** [comment]
I cannot reproduce this issue on neovim 0.1.1.

1. Please send me your vimrc (Are above three lines your vimrc?)
2. Please update to the latest lexima.vim
3. Please try the original vim

**Comment by h3st** [comment]
Those three lines were the entire vimrc. But it turned out I had some cruft left over in $vimdir/plugins that I'd forgotten to clean out; emptying that dir removed the issue. Sorry for the inconvenience.
