### ISSUE TITLE
Add ability to move cursor after closing bracket in new line

### ISSUE THREAD

**Issue by vitor-faiante** [cohama/lexima.vim#48]
When you are writing for example a function like so:

```php
public function helloWorld() {|}
```

When you press <CR> it will be like so:

```php
public function helloWorld() {
    |
}
```

Which is all ok but once you finish everything it would be ideal to be able to press } and then the cursor move to the position after the closing parentheses like so:

```php
public function helloWorld() {
    return "hello world";
}|
```

The same would apply to () and [] as those can be used in many languages (I am a PHP dev) to denote things like arrays, and function parameters etc.

Thanks.

**Comment by cohama** [comment]
You can do this by adding following rules to your vimrc.

```vim
call lexima#add_rule({'char': '}', 'at': '\%#\n\s*}', 'leave': '}'})
call lexima#add_rule({'char': ']', 'at': '\%#\n\s*]', 'leave': ']'})
call lexima#add_rule({'char': ')', 'at': '\%#\n\s*)', 'leave': ')'})
```

**Comment by cohama** [comment]
any updates?

**Comment by vitor-faiante** [comment]
@cohama I have tried it and it worked.
