### ISSUE TITLE
Don't expand if popup menu is available (on completion menu) on <CR>

### ISSUE THREAD

**Issue by josueetcom** [cohama/lexima.vim#49]
Hi! I'm really enjoying your plugin, but because I'm using the AutoComplPop plugin things were not working correctly when I pressed enter to select a completion from the pop up menu.

So, I had to change this one line in autoload/lexima/insmode.vim inside the function lexima#insmode#_expand(char) Line 93 from:

if !has_key(s:map_dict, char) || mode() !=# 'i'

to 

if !has_key(s:map_dict, char) || mode() !=# 'i' || pumvisible() && a:char ==# '<CR>'

That way, if the pop up menu for completion is visible (AutoComplPop shows it while typing a letter/word) then the mapping for <CR> will return the default <CR> instead of going to a new line. After this change it all works fantastically!

**Comment by cohama** [comment]
Thanks for your idea.
But your code breaks triggering abbreviation expansion.

I have fixed this problem by other way.
Please see #43.
