### ISSUE TITLE
Add Elixir endwise rules

### ISSUE THREAD

**Issue by hauleth** [cohama/lexima.vim#54]
It should be simple as almost all needed `end` entries happen after `do`.

**Comment by cohama** [comment]
Added. (import from ruby's rule)
Please try `elixir-endwise-rule` branch.

Since I have not written Elixir, I don't know whether this rule is correct or not.

**Comment by hauleth** [comment]
Seems ok, but part `\%(\s*|.*|\)\?` is unneeded in Elixir as it is invalid syntax.

**Comment by cohama** [comment]
Thank you for reviewing. I have merged to the master branch!
