### ISSUE TITLE
Neovim : <C-h> needs to be overridden

### ISSUE THREAD

**Issue by aemb** [cohama/lexima.vim#55]
I want to bind `<C-h>` in neovim to move cursor left in insert mode. But it can't work.
```{vim}
nnoremap <C-h> <C-w>h " only C-h does not work.
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
```
This is what I added to my `.vimrc` to try to make it work and it still doesn't work :
```{vim}
if has('nvim')
  " Hack to get C-h working in NeoVim
  nmap <BS> <C-W>h
endif
```
`verbose imap <BS>` gives me this result
```{vim}
i  <BS>        * lexima#expand('<BS>', 'i')
        Last set from ~/.vim/plugged/lexima.vim/autoload/lexima/insmode.vim
```
Someone [here](https://github.com/neovim/neovim/issues/2048#issuecomment-202343093)  told me this :
> @aemb You are mapping <BS> in normal mode, not insert mode, so the plugin takes over. It might override it even if you do map it in insert mode, but that will depend on how well behaved it is.

How can I override the plugin mapping ?

**Comment by cohama** [comment]
You need to learn about mappings. See `:help map-overview`
lexima.vim does not touch normal mappings.
If you want to override any key in insert mode, use `imap` instead of `nmap`.

Pleae note that your `imap` is put after `lexima#init()` since grantee the definition order.

```vim
" force init lexima.vim
call lexima#init()
" override the lexima's mapping
inoremap <C-h> <Left>
```
