### ISSUE TITLE
Vim patch 7.4.2117: Deleting an augroup that still has autocmds give a warning

### ISSUE THREAD

**Issue by AlexMasterov** [cohama/lexima.vim#59]
[Remove an augroup after initialization](https://github.com/cohama/lexima.vim/commit/1e584cc6b6db44ea974d9551dae80d2f5db9f904) now gives warning:
> W19: Deleting augroup that is still in use

Ref: [Vim patch 7.4.2117](https://github.com/vim/vim/commit/f2c4c391192cab6e923b1a418d4af09106fba25f)

**Comment by cohama** [comment]
Fixed with #60
