### ISSUE TITLE
CR inserts new line when deoplete's completion menu is displayed in Neovim.

### ISSUE THREAD

**Issue by kwinczek** [cohama/lexima.vim#63]
Minimal config:

```
call plug#begin('~/.config/nvim/minimal-plugged')

Plug 'Shougo/deoplete.nvim'
Plug 'cohama/lexima.vim'

call plug#end()

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_refresh_always = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_camel_case = 1
let g:deoplete#file#enable_buffer_path = 1
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
set omnifunc=syntaxcomplete#Complete
set completeopt=longest,menuone,preview,noinsert
```

Steps to reproduce:
1. Start nvim by `nvim -u minimal.init.vim`.
2. Insert couple of string to populate buffer completion for Deoplete.
3. Attempt word completion, let deoplete preselect first completion candidate.
4. Press <CR> to accept completion.

Outcome:
Upon completion accepted by <CR> cursor is moved to new line.

Expected outcome:
Completion should happen without entering new line.

Both lexima and deoplete are latest versions. Neovim is 0.1.5.

Please see gif demonstrating the issue:
![lexima_cr_issue](https://cloud.githubusercontent.com/assets/796021/19381186/2f17c328-9203-11e6-8884-5acb9d3c0df4.gif)

**Comment by cohama** [comment]
lexima.vim sends `<C-y>` before pressing `<CR>` to close complete popup. (See `:h omplete_CTRL-Y`.)

I think neovim's `<C-y>` doesn't work correctly.

Please try below.
1. Delete LINE 4 `Plug 'cohama/lexima.vim'` for minimal.init.vim.
2. Repeat 1 to 3 of your steps.
3. Press `<C-y>` instead of `<CR>`.

I tried with normal Vim (version 8.0.23) with neocomplete and nothing happend.

**Comment by kwinczek** [comment]
C-y accepts selected completion and closes the popup. That is without lexima installed.

**Comment by cohama** [comment]
I have found a work around.
Please add below in your `minimal.init.nvim` and please re-try.

```vim
let g:lexima_no_default_rules = 1
call lexima#set_default_rules()
call lexima#insmode#map_hook('before', '<CR>', "<C-]><Space><BS>")
```

**Comment by cohama** [comment]
If it is good, I will merge that change into the master.

**Comment by kwinczek** [comment]
With

```
let g:lexima_no_default_rules = 1

call plug#begin('~/.config/nvim/minimal-plugged')

Plug 'Shougo/deoplete.nvim'
Plug 'cohama/lexima.vim'

call plug#end()

call lexima#set_default_rules()
call lexima#insmode#map_hook('before', '<CR>', "<C-]><Space><BS>")

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_refresh_always = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_camel_case = 1
let g:deoplete#file#enable_buffer_path = 1
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
set omnifunc=syntaxcomplete#Complete
set completeopt=longest,menuone,preview,noinsert
```
CR enters new line without accepting completion at all. It leaves whatever was inserted in the first place.

**Comment by cohama** [comment]
Is it OK?

**Comment by kwinczek** [comment]
Oh, no, sorry, it should accept selected completion, it doesn't with configuration you provided.

**Comment by cohama** [comment]
Sorry, I misunderstood.
What you want is not insert new line but *accept* completion.

Please try below. (Add to the original `min.init.nvim`)
```vim
let g:lexima_no_default_rules = 1
call lexima#set_default_rules()
imap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"
```

**Comment by kwinczek** [comment]
This works exactly how I want it. Is it something that should be configured by user or do you want to merge that into lexima?

Oh, just checked, first two lines:

```
let g:lexima_no_default_rules = 1
call lexima#set_default_rules()
```
are not required, imap fixes the problem. Which makes me think, inoremap works as well, is there a need for imap?

**Comment by cohama** [comment]
Ok thanks.
I will merge this change for neovim.

These two lines are necessary to override lexima's default mapping. (but it depends on plugin manager you use)

`imap` is also necessary. If you use `inoremap`, lexima's `<CR>` features are no longer available.

**Comment by kwinczek** [comment]
Thank you very much for looking into this!
