### ISSUE TITLE
unexpected behavior after pressing ESC

### ISSUE THREAD

**Issue by atsepkov** [cohama/lexima.vim#64]
If I press a key within a second of pressing ESC, that key usually interacts with the text I input in some undesirable way.

For example, using arrow keys inserts something like A or D at the line above the cursor. Using h,j,k,l re-enters insert mode and inserts the character at the cursor location.

**Comment by cohama** [comment]
I can not reproduce that.

Please report 
- which kind of vim, vim or neovim, terminal or gui? (I'm sure it would be terminal)
- what version of vim
- minimal vimrc file which can reprodue the problem.

**Comment by avleen** [comment]
I just installed this plugin and also get this behavior.
ViM 7.4.160

It seems like if you press ESC and then quickly press an arrow key, this happens.
But if you wait about half a second, ViM leaves insert mode, and then things are OK.

**Comment by unphased** [comment]
Usually this type of sticky Esc issue is caused by a bind existing in vim that includes an escape. Improperly bound alt keystroke sequences will often do this.

check your ttimeoutlen value... 

http://www.polarhome.com/vim/manual/v57/options.html#'timeoutlen'

**Comment by cohama** [comment]
It would be caused not only vim but also shell or terminal.
Please check the post.
https://www.johnhawthorn.com/2012/09/vi-escape-delays/
