### ISSUE TITLE
Inserting parens before other parens

### ISSUE THREAD

**Issue by jonashaag** [cohama/lexima.vim#72]
Current behaviour:

```
Before        Input         After
------------------------------------
|()           (             (|)()
```

Sometimes it's the right thing to insert the closing parenthesis as well, but sometimes it's not what the user wants. I believe the following outcomes are legitimate use cases:

```
      Before        Input         After
------------------------------------
(1)   |(...)        (             (|)(...)
(2)   |(...)        foo(          (|(...)
(3)   |(...)        foo(          (|(...))
```

- Example for case (1): Changing array access of a variable to array access of a function result: `a[i] -> foo()[i]`
- Example for case (2): Calling a function with an existing expression as argument: `(x + 1) * 2 -> foo((x + 1) * 2)`
- Case (3) is like (2) but auto-closes the paren.

My suggestion is to never insert a closing paren if the symbol following the cursor is a paren: Having to type a closing paren in some situations lexima doesn't support is perfectly fine. What annoys me is deleting an incorrectly inserted paren because it means I have to leave insert mode, press L, press X, and enter insert mode again.

**Comment by jonashaag** [comment]
This also bugs me when trying to wrap a word in quotes, e.g. `|foo  --> ' --> '|'foo`

**Comment by anthrotype** [comment]
I found this plugin https://github.com/Raimondi/delimitMate seems to do the right thing in this case

**Comment by cohama** [comment]
This is intended.
It is sometimes good but sometimes annoying, even for me.


My choice is that
- alywas auto-clossing parens is easy to predict for users.
- omitting a closing paren sometimes breaks dot-repeatable


In these case, I often use vim-surroud.
