### ISSUE TITLE
Ctrl-h in insert mode

### ISSUE THREAD

**Issue by arwtyxouymz** [cohama/lexima.vim#73]
Hi

I use lexima.vim and it is very useful plugin.
But I wonder if lexima has the feature what i want to do.

For example, If I input `(`, lexima complete `)` automatically.
So my cusrsor state become `(|)`.
In this state, if I input `Ctrl+h`, only opening bracket is deleted, and the state become `|)`.
I want to delete closing bracket too.

Does the lexima have this feature?

**Comment by hydeik** [comment]
I added following new rules in my vimrc.

``` vim
call lexima#add_rule({'char': '<C-h>', 'at': '(\%#)',   'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': '{\%#}',   'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': '\[\%#\]', 'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': '"\%#"',   'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': "'\\%#'",  'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': '`\%#`',   'delete': 1})
```

Hope this helps you.

**Comment by cohama** [comment]
Added `g:lexima_ctrlh_as_backspace` option.

Please add below in your vimrc.
```vim
let lexima_ctrlh_as_backspace = 1
```

You can always use `<C-h>` as `<BS>`.
