### ISSUE TITLE
Not clear how to get past closing bracket with space rules

### ISSUE THREAD

**Issue by stevehanson** [cohama/lexima.vim#76]
The `g:lexima_enable_space_rules` rule conveniently adds the closing space when I use a space after the opening bracket but it's unclear how I can get past the closing bracket.

    Before        Input       After         Expected
    -------------------------------------------------
    { foo| }       }          { foo} }      { foo }|
    -------------------------------------------------

I've tested with [jiangmiao/auto-pairs](https://github.com/jiangmiao/auto-pairs) and [Raimondi/delimitMate](https://github.com/Raimondi/delimitMate), and they both have the behavior I expect when using the default configuration.

**Comment by cohama** [comment]
Thanks for reporting.
Implemented.
