### ISSUE TITLE
<C-j>, <C-m> and others should be used in the same manner as Enter

### ISSUE THREAD

**Issue by kantuin** [cohama/lexima.vim#91]
I'm using my custom mappings which include <CR>. But lexima.vim doesn't apply newline rules like enter key.

**Comment by cohama** [comment]
Not should because vim distinguishes these keys.
Someone (including me!) may set different mapping with `<CR>`.
But you can customize the default behavior by below.

```vim
" <C-j> as <CR>
call lexima#insmode#define_altanative_key('<C-j>', '<Enter>')
```

I'm sorry that `lexima#insmode#define_altanative_key` function is now undocumented.
In the future, it will be public
