### ISSUE TITLE
Lexima#add_rule for 'char': '%'

### ISSUE THREAD

**Issue by brainclone** [cohama/lexima.vim#92]
Hi, on vim 8.1. I am trying to add the following rule in my ~/.vim/after/ftplugin/html/html.vim:
{#} + '%' => {% # %}
(# is the cursor.)

Here is the code from ~/.vim/after/ftplugin/html/html.vim (I also tried the path:~/.vim/after/ftplugin/html.vim)  with line numbers: 
 8 call lexima#add_rule({
  9     \ 'char': '%',
 10     \ 'at\': '{\%#}',
 11     \ 'input_after': '<Space><Space>%',
 12     \ 'mode': 'i',
 13     \ 'leave': 1,
 14     \ 'filetype': ['html', 'jinja', 'htmljinja', 'django', 'htmldjango', 'liquid', 'twig', 'html.twig', 'mako', 
 15     \ })

This does not work. As I put this in the .vim/after directory for 'html' filetype, this should work at least for html files. Thanks,

Brain.Clone

**Comment by cohama** [comment]
`lexima#add_rule` should put on `.vimrc` (e.g. `~/.vim/vimrc`), not on `ftplugin`.
This rule will only works with what is listed in the filetype key.

**Comment by brainclone** [comment]
Thank you for your reply. I moved them into .vimrc: (as this is loaded before the plugins, I made autocmd for them)
Still no luck.

" lexima rules for '%','<','<Space>'
autocmd filetype html call lexima#add_rule({
    \ 'char': '%',
    \ 'at\': '{\%#}',
    \ 'input_after': '<Space><Space>%',
    \ 'mode': 'i', " This is redundant as 'i' is default.
    \ 'leave': 1,
    \ 'filetype': 'html',
    \ })
autocmd filetype html call lexima#add_rule({
    \ 'char': '<',
    \ 'input_after': '>',
    \ 'filetype': ['html', 'jinja', 'htmljinja', 'django', 'htmldjango', 'liquid', 'twig', 'html.twig', 'mako', 'xml'],
    \ })
autocmd filetype html call lexima#add_rule({
    \ 'char': '<Space>',
    \ 'at': '{{\%#',
    \ 'input_after': '<Space>',
    \ 'filetype': ['html', 'jinja', 'htmljinja', 'django', 'htmldjango', 'liquid', 'twig', 'html.twig', 'mako', 'xml'],
    \ })
